### ISSUE TITLE
Github Pages build workflow failing due to invalid YAML front matter

### ISSUE THREAD

**Issue by donmarvex** [zero-to-mastery/CSS-Art#280]
This error occurs during the build workflow in github actions.

Apart from the front matter specified in the root `README.md` file, there is also another `README.md` file in `Art/confusionmatrix98/README.md`. 

The error is displayed below;
![Screenshot (301)](https://user-images.githubusercontent.com/32850163/170982897-e49ea253-f2e9-40cb-a2e1-67155f2114b9.png)

Another `README.md` file also exists in the repository as seen from the previous successful deployment
![Screenshot (304)](https://user-images.githubusercontent.com/32850163/170983127-823ef13c-37f4-435b-ada4-42681b8e1b88.png)

No YAML front matter is specified in this file;
![Screenshot (303)](https://user-images.githubusercontent.com/32850163/170983256-d54c9c20-0e5b-4328-95cd-f9c26bc935e0.png)

Perhaps, we can exclude this file or delete and run the build workflow to see if this error is rectified @sophiabrandt

**Comment by donmarvex** [comment]
I think the build workflow should be run again and the issue should be resolved.

**Comment by sophiabrandt** [comment]
Hm. It looks like I cannot trigger the workflow manually. 🤷

**Comment by donmarvex** [comment]
> Hm. It looks like I cannot trigger the workflow manually. 🤷

Well. I tried to re-run the workflow but it still failed. I see you ran it also again. 
I've also tried to have a look at the file but I don't seem to find anything _**yet**_ that would result in this error

**Comment by donmarvex** [comment]
I did a quick search and discovered another `README.md` file in another location. I'll delete and see if it works.

**Comment by donmarvex** [comment]
Well, doesn't look like that solved the issue. Maybe we need another pair of eyes to have a look at this. This would prevent any new contributions from getting added to the web application.

**Comment by donmarvex** [comment]
Hi @sophiabrandt, I may have found a quite straightforward solution to this issue.

GitHub pages builds from the root directory and when a front matter is specified (in this case in the README.md file), it attempts to read the contents within the 3 dashes. However, in markdown, those 3 dashes represent a horizontal line but for YAML, specifies front matter.

I worked on my fork and decided to build a separate GitHub page for the project, removed the three dashes from the root `README.md` and the build was successful. You can check it out [`here`](https://github.com/donmarvex/CSS-Art/runs/6708558351?check_suite_focus=true)
![Screenshot (314)](https://user-images.githubusercontent.com/32850163/171634820-d1953c78-5afc-4158-b5c1-6a54a47eaa75.png)

I think prior to this time, the `Build with Jekyll` job built from the other README.md files in the sub directories of the `Art` folder. Now, as we removed those files, all that was left was the root `README.md` file which had invalid content wrt to YAML formatting and prevented the entire build process from getting completed.

**Comment by donmarvex** [comment]
Deployment successful!
https://github.com/zero-to-mastery/CSS-Art/actions/runs/2442530855
