### ISSUE TITLE
Cracked link dailycssimages.com

### ISSUE THREAD

**Issue by Cor4zon** [zero-to-mastery/CSS-Art#337]
Hi! I found a problem on [A Beginner’s Guide to Pure CSS Images](https://codepen.io/mikemang/post/a-beginner-s-guide-to-pure-css-images). Please check the link http://dailycssimages.com/

<img width="792" alt="image" src="https://user-images.githubusercontent.com/71446920/201508317-232ec2de-9ad3-44ef-a5e6-e2f882c8f9a2.png">

I think it was cracked.

**Comment by donmarvex** [comment]
Hi @Cor4zon , thanks for spotting this out. Could you make a pull request to fix this?

**Comment by prachic17** [comment]
I think we need to cut down this part as dailycssimages.com is no longer available.
