### ISSUE TITLE
Open Contribution?

### ISSUE THREAD

**Issue by KalebArmbrust** [zero-to-mastery/CSS-Art#381]
@MattCSmith Is this repo open to contribute or is it a part of hacktober fest only?

**Comment by ankushtripathii** [comment]
open for contribution?

**Comment by aryashsaxena** [comment]
if is there any issue then let me know I can help you.

**Comment by eshan-one** [comment]
Can we still contribute to the repo  and get our pull requests  merged??

**Comment by l-white** [comment]
@KalebArmbrust @ankushtripathii @eshan-one I have been approving / merging pull requests on occasion, but this repo might be archived at some point. One of the challenges is that if there is any broken HTML in even just one contribution, it breaks the layout. That said, if you have made contributions recently or wish to, I will try to take a look. Hope that helps, at least for the moment.

**Comment by eshan-one** [comment]
Sure @l-white thanks for the message
